### ISSUE TITLE
AUR package update

### ISSUE THREAD

**Issue by Monirzadeh** [Roshan-R/termv#17]
hi
please update Aur package to 1.2 if it possible for you.

**Comment by darkelectron** [comment]
Would creating a different package called `termv` be better? This one would be stable and the `-git` version would be an unstable version. 

Thought of creating it, but thought I should ask first.

**Comment by Roshan-R** [comment]
It would be amazing if you could create another AUR package for termv
Just a side note, the existing AUR package does not infact use git clone rather uses the releases

**Comment by darkelectron** [comment]
...and done! 

https://aur.archlinux.org/packages/termv/

**Comment by Roshan-R** [comment]
Thanks @darkelectron for the package!
I'll update the readme after testing it :)

**Comment by odnar-dev** [comment]
@darkelectron - wrong dependencies!!
this script use `curl` not `wget`
also it use `gawk`

**Comment by darkelectron** [comment]
@odnar-dev, thanks.
Seeing that `xdo` is optional, should I add it under `optdepends`?

**Comment by Roshan-R** [comment]
> @odnar-dev, thanks. Seeing that `xdo` is optional, should I add it under `optdepends`?

Yeah, I think it would be better to add it to optdepends

**Comment by darkelectron** [comment]
I have updated the PKGBUILD.

**Comment by Roshan-R** [comment]
Looks good now, i have updated the project README
