### ISSUE TITLE
`brew` installation fails on macOS

### ISSUE THREAD

**Issue by habi** [Roshan-R/termv#31]
I wanted to `brew tap Roshan-R/termv https://github.com/Roshan-R/homebrew-termv` on macOS 12.4 (21F79), but the installation fails with the error message below.
```
==> Tapping roshan-r/termv
Cloning into '/usr/local/Homebrew/Library/Taps/roshan-r/homebrew-termv'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 13 (delta 3), reused 6 (delta 2), pack-reused 0
Receiving objects: 100% (13/13), done.
Resolving deltas: 100% (3/3), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/roshan-r/homebrew-termv/termv.rb
termv: wrong number of arguments (given 1, expected 0)
Error: Cannot tap roshan-r/termv: invalid syntax in tap!
```

**Comment by Roshan-R** [comment]
Think it is an error due to my homebrew tap. I don't have a mac machine to test this on, will fix it when i get my hands on one :smile:

**Comment by Roshan-R** [comment]
I have updated the homebrew-termv tap repo and it seems like this works, could you try running it and see if it works @habi?

**Comment by habi** [comment]
Works like a charm, thanks for the perseverance!
