### ISSUE TITLE
Is there a way to use this project with my own m3u links?

### ISSUE THREAD

**Issue by petrusd10s** [Roshan-R/termv#32]
Basically the question itself. It would be a remote list

**Comment by Roshan-R** [comment]
Termv uses a lot of json manipulation that is specific to the way how [iptv-org](https://iptv-org.github.io/iptv/index.m3u) structures it's json file. So I don't think just changing the url for the list would suffice.

But I am interested in creating some sort of way for users to choose another list. 
Maybe an alternate source?

**Comment by Roshan-R** [comment]
So the solution was to let the user host a new json file and point to it using the environment variable TERMV_API_URL.
This has been merged to the main branch.
