### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 10

### ISSUE THREAD

**Issue by m040601** [Roshan-R/termv#40]
Thanks for your work on this tool. Love its simplicity and eficiency.

For some time now it stopped working on my system.
I cant remember when I last used it, 2022 ?. But I remember clearly it was working fine some time ago.

I'm on Archlinux. I've tried both, https://aur.archlinux.org/packages/termv which installs the v1.3 you have released on github or https://aur.archlinux.org/packages/termv-git which pulls whatever is the latest you have commited on github.

Both give this error

```
parse error: Invalid numeric literal at line 1, column 10
```

Tried  deleting ~/.cache/termv and ~/.config/termv and starting fresh. Same problem. 

I alread read, https://github.com/Roshan-R/termv/issues/35 and something about a "fix branch" . Somebody talks about a 

> Works without flaws now 

 But the latest release you have on github is still from December 2022.

**Comment by diffficult** [comment]
don't install from repos, just clone the `fix` branch and install that one. 

You can do that with `$ git clone --branch fix https://github.com/Roshan-R/termv.git ` and then just following the `README.md` instructions for installing.

**Comment by Roshan-R** [comment]
Oops, thought I resolved this already, I'll create a new release

**Comment by Roshan-R** [comment]
I have created a new release, waiting for the maintainer of the AUR package to update it. Meanwhile the solution said by @diffficult seems to be a workaround

**Comment by diffficult** [comment]
thanks man, I will check it out later on and reinstall from the AUR.

**Comment by darkelectron** [comment]
> I have created a new release, waiting for the maintainer of the AUR package to update it. Meanwhile the solution said by @diffficult seems to be a workaround

I was waiting on the "tag rename" (#41). I have updated the AUR package.

**Comment by m040601** [comment]
I've tried it again today. Seems to be working fine.

I'm on Archlinux, using, https://aur.archlinux.org/packages/termv which currently installs the v1.4 you have released on github.

Thanks also to "darkelectron" for taking care of the PKGBUILD.

**Comment by Roshan-R** [comment]
Thanks to everyone for their support to this project! 
Closing the Issue since it has been resolved
